spring:
    application:
        name: pub-sub
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:13306/pub_sub
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update